#!/usr/bin/env python3
"""
This module contains the async_comprehension coroutine.
"""

from typing import List
import importlib

async_generator = importlib.import_module('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Coroutine that collects 10 random numbers using an async comprehension
    over async_generator.

    Returns:
        List[float]: A list of 10 random numbers generated by async_generator.
    """
    return [number async for number in async_generator()]
